import { TutorialStep } from './TutorialOverlay';

export const getTutorialSteps = (
  t: (key: string) => string,
): Record<string, TutorialStep[]> => ({
  onboarding: [
    {
      id: 'welcome-overview',
      target: '[data-tutorial="wallet-overview"]',
      title: t('home:tutorial.steps.welcome_overview.title'),
      content: t('home:tutorial.steps.welcome_overview.content'),
      position: 'auto',
      action: 'none',
      hidePrevious: true,
      skipable: true,
    },
    {
      id: 'multi-chain-intro',
      target: '[data-tutorial="wallet-selector"]',
      title: t('home:tutorial.steps.multi_chain_intro.title'),
      content: t('home:tutorial.steps.multi_chain_intro.content'),
      position: 'auto',
      action: 'click',
      skipable: false,
    },
    {
      id: 'find-switch-chain',
      target: '[data-tutorial="chain-selector"]',
      title: t('home:tutorial.steps.find_switch_chain.title'),
      content: t('home:tutorial.steps.find_switch_chain.content'),
      position: 'auto',
      action: 'click',
      skipable: false,
    },
    {
      id: 'select-ethereum',
      target: '[data-tutorial="chain-item-eth"]',
      title: t('home:tutorial.steps.select_ethereum.title'),
      content: t('home:tutorial.steps.select_ethereum.content'),
      position: 'auto',
      action: 'click',
      skipable: false,
      hidePrevious: true,
    },
    {
      id: 'ethereum-sync-waiting',
      target: '',
      title: t('home:tutorial.steps.ethereum_sync_waiting.title'),
      content: t('home:tutorial.steps.ethereum_sync_waiting.content'),
      position: 'auto',
      action: 'click',
      skipable: false,
      hidePrevious: true,
      syncHint: t('home:tutorial.steps.ethereum_sync_waiting.sync_hint'),
    },
    {
      id: 'ethereum-tokens',
      target: '[data-tutorial="tokens-section"]',
      title: t('home:tutorial.steps.ethereum_tokens.title'),
      content: t('home:tutorial.steps.ethereum_tokens.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'add-token-demo',
      target: '[data-tutorial="add-token-button"]',
      title: t('home:tutorial.steps.add_token_demo.title'),
      content: t('home:tutorial.steps.add_token_demo.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'receive-intro',
      target: '[data-tutorial="receive-button"]',
      title: t('home:tutorial.steps.receive_intro.title'),
      content: t('home:tutorial.steps.receive_intro.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'send-intro',
      target: '[data-tutorial="send-button"]',
      title: t('home:tutorial.steps.send_intro.title'),
      content: t('home:tutorial.steps.send_intro.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'swap-feature',
      target: '[data-tutorial="swap-button"]',
      title: t('home:tutorial.steps.swap_feature.title'),
      content: t('home:tutorial.steps.swap_feature.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'buy-sell-feature',
      target: '[data-tutorial="buy-sell-button"]',
      title: t('home:tutorial.steps.buy_sell_feature.title'),
      content: t('home:tutorial.steps.buy_sell_feature.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'activity-section',
      target: '.ant-tabs-tab[data-node-key="activity"]',
      title: t('home:tutorial.steps.activity_section.title'),
      content: t('home:tutorial.steps.activity_section.content'),
      position: 'auto',
      action: 'click',
      skipable: false,
    },
    {
      id: 'activity-explanation',
      target: '[data-tutorial="transactions-table"]',
      title: t('home:tutorial.steps.activity_explanation.title'),
      content: t('home:tutorial.steps.activity_explanation.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'contacts-section',
      target: '.ant-tabs-tab[data-node-key="contacts"]',
      title: t('home:tutorial.steps.contacts_section.title'),
      content: t('home:tutorial.steps.contacts_section.content'),
      position: 'auto',
      action: 'click',
      skipable: false,
    },
    {
      id: 'contacts-explanation',
      target: '[data-tutorial="contacts-table"]',
      title: t('home:tutorial.steps.contacts_explanation.title'),
      content: t('home:tutorial.steps.contacts_explanation.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'extended-menu-intro',
      target: '[data-tutorial="extended-menu"]',
      title: t('home:tutorial.steps.extended_menu_intro.title'),
      content: t('home:tutorial.steps.extended_menu_intro.content'),
      position: 'left',
      action: 'none',
      skipable: false,
    },
    {
      id: 'address-management',
      target: '[data-tutorial="wallet-selector"]',
      title: t('home:tutorial.steps.address_management.title'),
      content: t('home:tutorial.steps.address_management.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
    {
      id: 'tutorial-complete',
      target: 'body',
      title: t('home:tutorial.steps.tutorial_complete.title'),
      content: t('home:tutorial.steps.tutorial_complete.content'),
      position: 'auto',
      action: 'none',
      skipable: false,
    },
  ],
});
