name: Build And Upload Extension Zip

on:
  push:
    branches: [master]
    tags:
      - v1.*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      # - uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build extensions
        run: yarn build:all

      - name: Upload Chrome extension
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: dist-zip/ssp-wallet-chrome-*.zip

      - name: Upload Firefox extension
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: dist-zip/ssp-wallet-firefox-*.zip
