name: Deterministic Build

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true

jobs:
  deterministic-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
          
      - name: Build deterministic packages
        run: bash scripts/deterministic-build.sh
          
      - name: Extract version
        id: version
        run: echo "version=${{ github.event.inputs.tag || github.ref_name }}" >> $GITHUB_OUTPUT
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deterministic-build-${{ steps.version.outputs.version }}
          path: |
            ssp-wallet-*.zip*
            SHA256SUMS
            
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ssp-wallet-chrome-${{ steps.version.outputs.version }}.zip
            ssp-wallet-firefox-${{ steps.version.outputs.version }}.zip
            SHA256SUMS
          body: |
            ## Deterministic Build - ${{ steps.version.outputs.version }}
            
            This release contains deterministic builds for both Chrome and Firefox.

            **GPG Verification:** `gpg --verify SHA256SUMS.asc SHA256SUMS`

            **Files Verification:** `sha256sum -c SHA256SUMS`
            
            **Reproduction:** `git checkout ${{ steps.version.outputs.version }} && npm run build:deterministic`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}